"""crear tabla tasks

Revision ID: ef16a46fbf6f
Revises: b25cfd816d78
Create Date: 2026-07-15 17:10:34.144165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef16a46fbf6f'
down_revision: Union[str, Sequence[str], None] = 'b25cfd816d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points_value', sa.Integer(), server_default='10', nullable=False),
    sa.Column('priority', sa.Enum('BAJA', 'MEDIA', 'ALTA', name='task_priority'), nullable=False),
    sa.Column('frequency', sa.Enum('unica', 'diaria', 'semanal', name='task_frequency'), server_default='unica', nullable=False),
    sa.Column('status', sa.Enum('pendiente', 'completada', 'cancelada', name='task_status'), server_default='pendiente', nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_index(op.f('ix_users_firebase_id'), 'users', ['firebase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_firebase_id'), table_name='users')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_id'], unique=True)
    op.drop_table('tasks')
    # ### end Alembic commands ###
